export const CELE_TEMPLATES = {
  formula: {
    title: 'Formula Sheet Template',
    fields: ['Subject', 'Topic', 'Subtopic', 'Formula Name', 'Formula (LaTeX Supported)', 'Description', 'Variables', 'Units', 'Conditions', 'Applications', 'Related Formulas', 'References'],
  },
  question: {
    title: 'Question Bank Template',
    fields: ['Subject', 'Topic', 'Difficulty', 'Question', 'Choice A', 'Choice B', 'Choice C', 'Choice D', 'Correct Answer', 'Explanation', 'Formula Reference', 'Board Year', 'Source', 'Tags'],
  },
};

const esc = (value) => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const download = (parts, filename, type) => { const url = URL.createObjectURL(new Blob(parts, { type })); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url); };
const crc32 = (bytes) => { let c = -1; for (const b of bytes) { c ^= b; for (let n = 0; n < 8; n += 1) c = (c >>> 1) ^ (0xEDB88320 & -(c & 1)); } return (c ^ -1) >>> 0; };
const u16 = (n) => [n & 255, (n >>> 8) & 255]; const u32 = (n) => [n & 255, (n >>> 8) & 255, (n >>> 16) & 255, (n >>> 24) & 255];
const zip = (entries) => { const encoder = new TextEncoder(); const files = entries.map(([name, text]) => ({ name: encoder.encode(name), data: encoder.encode(text) })); let offset = 0; const local = []; const central = []; for (const file of files) { const crc = crc32(file.data); const header = [80, 75, 3, 4, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...u32(crc), ...u32(file.data.length), ...u32(file.data.length), ...u16(file.name.length), 0, 0]; local.push(new Uint8Array([...header, ...file.name, ...file.data])); central.push(new Uint8Array([80, 75, 1, 2, 20, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...u32(crc), ...u32(file.data.length), ...u32(file.data.length), ...u16(file.name.length), 0, 0, 0, 0, 0, 0, 0, 0, ...u32(offset), ...file.name])); offset += header.length + file.name.length + file.data.length; } const centralLength = central.reduce((sum, part) => sum + part.length, 0); return new Blob([...local, ...central, new Uint8Array([80, 75, 5, 6, 0, 0, 0, 0, ...u16(files.length), ...u16(files.length), ...u32(centralLength), ...u32(offset), 0, 0])], { type: 'application/zip' }); };

export const downloadTemplate = async (kind, format) => {
  const template = CELE_TEMPLATES[kind]; const fields = template.fields; const slug = `cele-pilot-${kind}-template`;
  if (format === 'csv') return download([`${fields.map(x => `"${x}"`).join(',')}\n`], `${slug}.csv`, 'text/csv');
  if (format === 'xlsx') { const cells = fields.map((field, i) => `<c r="${String.fromCharCode(65 + i)}1" t="inlineStr"><is><t>${esc(field)}</t></is></c>`).join(''); const sheet = `<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1">${cells}</row></sheetData></worksheet>`; const contentTypes = `<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`; return download([zip([['[Content_Types].xml', contentTypes], ['_rels/.rels', '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'], ['xl/workbook.xml', '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Template" sheetId="1" r:id="rId1"/></sheets></workbook>'], ['xl/_rels/workbook.xml.rels', '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'], ['xl/worksheets/sheet1.xml', sheet]])], `${slug}.xlsx`, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); }
  if (format === 'docx') { const body = fields.map(field => `<w:p><w:r><w:t>${esc(field)}:</w:t></w:r></w:p>`).join(''); const doc = `<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>${esc(template.title)}</w:t></w:r></w:p>${body}<w:sectPr/></w:body></w:document>`; return download([zip([['[Content_Types].xml', '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'], ['_rels/.rels', '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'], ['word/document.xml', doc]])], `${slug}.docx`, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'); }
  const { jsPDF } = await import('jspdf'); const pdf = new jsPDF(); pdf.setFontSize(16); pdf.text(`CELE Pilot ${template.title}`, 20, 20); pdf.setFontSize(11); fields.forEach((field, index) => pdf.text(`${field}:`, 20, 34 + index * 10)); pdf.save(`${slug}.pdf`);
};
