import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { CalendarDays, Pencil, Search, SlidersHorizontal, Trash2 } from 'lucide-react';
import { Area, AreaChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { eachDayOfInterval, format, isSameDay, startOfDay, startOfMonth, startOfWeek, subDays } from 'date-fns';
import { firebaseApi } from '@/api/firebaseClient';
import { useAuth } from '@/lib/AuthContext';
import { useStudyHistory } from '@/hooks/useStudyHistory';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';

const SUBJECTS = ['All', 'PSAD', 'MSTE', 'HGE'];
const COLORS = { PSAD: '#8b5cf6', MSTE: '#3b82f6', HGE: '#10b981' };
const recordDate = (record) => { const value = record?.startTime || record?.endTime || record?.date; const date = value?.toDate ? value.toDate() : value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? date : null; };
const minutes = (record) => Math.max(0, Number(record?.durationMinutes ?? record?.duration_minutes ?? 0));
const minuteText = (value) => `${Math.round(Math.max(0, Number(value) || 0)).toLocaleString()} min`;
const order = (records) => [...records].sort((a, b) => (recordDate(b)?.getTime() || 0) - (recordDate(a)?.getTime() || 0));

export default function StudyHistory() {
  const { user, isAuthenticated } = useAuth();
  const { records, loading } = useStudyHistory(isAuthenticated ? user?.id : null);
  const [subject, setSubject] = useState('All'); const [range, setRange] = useState('all'); const [sort, setSort] = useState('newest'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState(null); const [editing, setEditing] = useState(false); const [selectedIds, setSelectedIds] = useState(new Set()); const [deleteRequest, setDeleteRequest] = useState(null); const [subjectMetric, setSubjectMetric] = useState('sessions');
  const completed = useMemo(() => records.filter((record) => recordDate(record)), [records]);
  const today = startOfDay(new Date()); const week = startOfWeek(new Date(), { weekStartsOn: 0 }); const month = startOfMonth(new Date());
  const totalFor = (start) => completed.filter((record) => recordDate(record) >= start).reduce((sum, record) => sum + minutes(record), 0);
  const summary = useMemo(() => ({ today: totalFor(today), week: totalFor(week), month: totalFor(month), total: completed.reduce((sum, record) => sum + minutes(record), 0) }), [completed]);
  const daily = useMemo(() => eachDayOfInterval({ start: subDays(today, 6), end: today }).map((day) => ({ day: format(day, 'EEE'), minutes: completed.filter((record) => isSameDay(recordDate(record), day)).reduce((sum, record) => sum + minutes(record), 0) })), [completed]);
  const subjectData = useMemo(() => ['PSAD', 'MSTE', 'HGE'].map((name) => { const sessions = completed.filter((record) => record.subject === name); const value = subjectMetric === 'sessions' ? sessions.length : sessions.reduce((sum, record) => sum + minutes(record), 0); return { name, value, sessions: sessions.length, minutes: sessions.reduce((sum, record) => sum + minutes(record), 0) }; }).filter((entry) => entry.value > 0), [completed, subjectMetric]);
  const stats = useMemo(() => { const values = completed.map(minutes); const bySubject = ['PSAD', 'MSTE', 'HGE'].map((name) => ({ name, minutes: completed.filter((record) => record.subject === name).reduce((sum, record) => sum + minutes(record), 0) })).filter((entry) => entry.minutes > 0); const dates = new Set(completed.map((record) => format(recordDate(record), 'yyyy-MM-dd'))); let streak = 0; for (let day = today; dates.has(format(day, 'yyyy-MM-dd')); day = subDays(day, 1)) streak += 1; return { averageDay: dates.size ? summary.total / dates.size : 0, averageSession: values.length ? summary.total / values.length : 0, longest: Math.max(0, ...values), shortest: values.length ? Math.min(...values) : 0, most: [...bySubject].sort((a, b) => b.minutes - a.minutes)[0]?.name || '—', least: [...bySubject].sort((a, b) => a.minutes - b.minutes)[0]?.name || '—', streak }; }, [completed, summary.total]);
  const filtered = useMemo(() => { const needle = search.trim().toLowerCase(); const start = range === 'today' ? today : range === 'week' ? week : range === 'month' ? month : null; return records.filter((record) => (subject === 'All' || record.subject === subject) && (!start || (recordDate(record) && recordDate(record) >= start)) && (!needle || [record.subject, record.topic, record.subtopic, record.notes, record.date].filter(Boolean).join(' ').toLowerCase().includes(needle))).sort((a, b) => sort === 'longest' ? minutes(b) - minutes(a) : sort === 'oldest' ? (recordDate(a)?.getTime() || 0) - (recordDate(b)?.getTime() || 0) : (recordDate(b)?.getTime() || 0) - (recordDate(a)?.getTime() || 0)); }, [records, subject, range, sort, search]);
  const toggle = (id) => setSelectedIds((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const performDelete = async () => { if (!deleteRequest) return; const ids = deleteRequest.kind === 'all' ? records.map((record) => record.id) : deleteRequest.ids; if (deleteRequest.kind === 'all') await firebaseApi.studyHistory.deleteAll(); else if (ids.length === 1) await firebaseApi.studyHistory.delete(ids[0]); else await firebaseApi.studyHistory.bulkDelete(ids); setSelectedIds(new Set()); setEditing(false); setDeleteRequest(null); };
  if (loading) return <div className="min-h-[50vh] flex items-center justify-center text-muted-foreground">Loading study history…</div>;
  return <div className="space-y-5"><header className="flex items-center gap-3"><div className="flex-1"><h1 className="text-2xl font-bold">Study History</h1><p className="text-sm text-muted-foreground">Your synced study sessions and progress.</p></div>{records.length > 0 && <Button variant="outline" size="sm" onClick={() => { setEditing((value) => !value); setSelectedIds(new Set()); }}><Pencil className="mr-1 h-4 w-4" />{editing ? 'Cancel' : 'Edit'}</Button>}<CalendarDays className="text-primary" /></header>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Today', summary.today], ['This Week', summary.week], ['This Month', summary.month], ['Total', summary.total]].map(([label, value]) => <div className="glass-card p-4 transition-transform hover:-translate-y-0.5" key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{minuteText(value)}</p></div>)}</section>
    <section className="grid gap-4 md:grid-cols-2"><div className="glass-card p-4"><h2 className="font-semibold">Daily Study Minutes</h2>{completed.length ? <div className="mt-3 h-56"><ResponsiveContainer><AreaChart data={daily} margin={{ left: -18, right: 8, top: 10 }}><defs><linearGradient id="studyMinutes" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="hsl(var(--primary))" stopOpacity={0.38}/><stop offset="95%" stopColor="hsl(var(--primary))" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="day" tick={{ fontSize: 12 }} /><YAxis tickFormatter={(value) => `${value}m`} tick={{ fontSize: 12 }} /><Tooltip formatter={(value) => [minuteText(value), 'Study time']} /><Area type="monotone" dataKey="minutes" stroke="hsl(var(--primary))" strokeWidth={3} fill="url(#studyMinutes)" dot={{ r: 4, fill: 'hsl(var(--primary))' }} activeDot={{ r: 6 }} /></AreaChart></ResponsiveContainer></div> : <ChartEmpty />}</div><div className="glass-card p-4"><div className="flex items-center justify-between gap-2"><h2 className="font-semibold">Sessions per Subject</h2><div className="flex gap-1"><Button size="sm" variant={subjectMetric === 'sessions' ? 'default' : 'ghost'} onClick={() => setSubjectMetric('sessions')}>Sessions</Button><Button size="sm" variant={subjectMetric === 'minutes' ? 'default' : 'ghost'} onClick={() => setSubjectMetric('minutes')}>Minutes</Button></div></div>{subjectData.length ? <div className="mt-3 grid grid-cols-2 items-center gap-2"><div className="h-48"><ResponsiveContainer><PieChart><Pie data={subjectData} dataKey="value" nameKey="name" outerRadius={68}>{subjectData.map((entry) => <Cell key={entry.name} fill={COLORS[entry.name]} />)}</Pie><Tooltip formatter={(value) => subjectMetric === 'minutes' ? minuteText(value) : `${value} sessions`} /></PieChart></ResponsiveContainer></div><div className="space-y-2 text-sm">{subjectData.map((entry) => <div key={entry.name}><p className="font-medium">{entry.name}</p><p className="text-xs text-muted-foreground">{entry.sessions} sessions · {minuteText(entry.minutes)} · {summary.total ? Math.round((entry.minutes / summary.total) * 100) : 0}%</p></div>)}</div></div> : <ChartEmpty />}</div></section>
    <section className="glass-card p-4"><h2 className="font-semibold">Study Statistics</h2><div className="mt-3 grid grid-cols-2 gap-3 text-sm md:grid-cols-4">{[['Average / day', minuteText(stats.averageDay)], ['Average / session', minuteText(stats.averageSession)], ['Longest session', minuteText(stats.longest)], ['Shortest session', minuteText(stats.shortest)], ['Most studied', stats.most], ['Least studied', stats.least], ['Study streak', `${stats.streak} days`]].map(([label, value]) => <div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="font-medium">{value}</p></div>)}</div></section>
    <section className="glass-card space-y-3 p-4"><div className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4" /><h2 className="font-semibold">Filters</h2></div><div className="flex gap-2 overflow-x-auto">{SUBJECTS.map((name) => <Button key={name} size="sm" variant={subject === name ? 'default' : 'outline'} onClick={() => setSubject(name)}>{name}</Button>)}</div><div className="grid gap-2 md:grid-cols-3"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={range} onChange={(event) => setRange(event.target.value)}><option value="all">All time</option><option value="today">Today</option><option value="week">This week</option><option value="month">This month</option></select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="longest">Longest session</option></select><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Subject, topic, notes, date" value={search} onChange={(event) => setSearch(event.target.value)} /></div></div></section>
    <section className="space-y-3"><div className="flex justify-between"><h2 className="text-lg font-bold">Sessions</h2><span className="text-sm text-muted-foreground">{filtered.length} shown</span></div>{!records.length ? <div className="glass-card p-8 text-center"><CalendarDays className="mx-auto h-10 w-10 text-primary" /><p className="mt-3 font-medium">No study history yet.</p><Button className="mt-4" asChild><Link to="/timer">Start Studying</Link></Button></div> : filtered.length ? filtered.map((record) => <article key={record.id} className="glass-card flex items-center gap-3 p-4 transition-transform hover:-translate-y-0.5">{editing && <input type="checkbox" aria-label="Select study history record" checked={selectedIds.has(record.id)} onChange={() => toggle(record.id)} />}{editing ? <div className="flex-1"><RecordSummary record={record} /></div> : <button type="button" onClick={() => setSelected(record)} className="flex-1 text-left"><RecordSummary record={record} /></button>}<Button variant="ghost" size="icon" aria-label="Delete study history record" onClick={() => setDeleteRequest({ kind: 'single', ids: [record.id] })}><Trash2 className="h-4 w-4" /></Button></article>) : <div className="glass-card p-6 text-center text-muted-foreground">No sessions match these filters.</div>}</section>
    {editing && <div className="sticky bottom-4 z-20 flex flex-wrap gap-2 rounded-lg border bg-background p-3 shadow-lg"><Button variant="destructive" disabled={!selectedIds.size} onClick={() => setDeleteRequest({ kind: 'multiple', ids: [...selectedIds] })}>Delete Selected</Button><Button variant="destructive" onClick={() => setDeleteRequest({ kind: 'all', ids: records.map((record) => record.id) })}>Delete All</Button><Button variant="outline" onClick={() => { setEditing(false); setSelectedIds(new Set()); }}>Cancel</Button></div>}
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent>{selected && <><DialogHeader><DialogTitle>{selected.subject || 'Study'} session</DialogTitle></DialogHeader><dl className="grid grid-cols-2 gap-3 text-sm"><dt className="text-muted-foreground">Topic</dt><dd>{selected.topic || '—'}</dd><dt className="text-muted-foreground">Sub Topic</dt><dd>{selected.subtopic || '—'}</dd><dt className="text-muted-foreground">Start</dt><dd>{recordDate(selected)?.toLocaleString() || '—'}</dd><dt className="text-muted-foreground">Duration</dt><dd>{minuteText(minutes(selected))}</dd><dt className="text-muted-foreground">Notes</dt><dd>{selected.notes || '—'}</dd></dl></>}</DialogContent></Dialog>
    <Dialog open={Boolean(deleteRequest)} onOpenChange={(open) => !open && setDeleteRequest(null)}><DialogContent><DialogHeader><DialogTitle>Delete study history</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{deleteRequest?.kind === 'all' ? 'This will permanently delete all study history records. This action cannot be undone.' : deleteRequest?.kind === 'multiple' ? 'Are you sure you want to delete the selected study history records?' : 'Are you sure you want to delete this study history record?'}</p><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setDeleteRequest(null)}>Cancel</Button><Button variant="destructive" onClick={performDelete}>{deleteRequest?.kind === 'all' ? 'Delete All' : 'Delete'}</Button></div></DialogContent></Dialog></div>;
}

function ChartEmpty() { return <div className="flex h-56 flex-col items-center justify-center text-center text-muted-foreground"><span className="text-3xl">📈</span><p className="mt-2 text-sm">No study history yet.</p></div>; }
function RecordSummary({ record }) { const date = recordDate(record); return <div className="flex justify-between gap-3"><div><p className="font-semibold">📘 {record.subject || 'General'}</p>{record.topic && <p className="text-sm text-muted-foreground">{record.topic}{record.subtopic ? ` · ${record.subtopic}` : ''}</p>}<p className="mt-2 text-sm">🕒 {date ? date.toLocaleString() : '—'}</p></div><p className="font-semibold">⏱ {minuteText(minutes(record))}</p></div>; }
