import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { firebaseApi } from '@/api/firebaseClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { BarChart, Bar, PieChart, Pie, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { addDays, eachDayOfInterval, endOfMonth, format, isSameDay, isWithinInterval, parseISO, startOfDay, startOfMonth, startOfWeek, subDays } from 'date-fns';
import { CalendarDays, Search, SlidersHorizontal } from 'lucide-react';

const subjects = ['All', 'PSAD', 'MSTE', 'HGE'];
const COLORS = { PSAD: '#8b5cf6', MSTE: '#3b82f6', HGE: '#10b981', General: '#64748b' };
const minutes = (record) => Number(record.durationMinutes ?? record.duration_minutes ?? 0);
const asDate = (record) => parseISO(record.startTime || record.endTime || `${record.date}T12:00:00`);
const duration = (value) => value >= 60 ? `${Math.floor(value / 60)}h${value % 60 ? ` ${value % 60}m` : ''}` : `${value}m`;

function rangeFor(value, from, to) {
  const now = new Date();
  if (value === 'today') return { start: startOfDay(now), end: now };
  if (value === 'week') return { start: startOfWeek(now, { weekStartsOn: 1 }), end: now };
  if (value === 'month') return { start: startOfMonth(now), end: now };
  return from && to ? { start: startOfDay(parseISO(from)), end: addDays(startOfDay(parseISO(to)), 1) } : null;
}

function calculateStats(records) {
  const completed = records.filter((item) => item.completed && item.sessionType !== 'Break' && item.sessionType !== 'Long Break');
  const total = completed.reduce((sum, item) => sum + minutes(item), 0);
  const now = new Date();
  const within = (start) => completed.filter((item) => asDate(item) >= start).reduce((sum, item) => sum + minutes(item), 0);
  const activeDates = new Set(completed.map((item) => format(asDate(item), 'yyyy-MM-dd')));
  let current = 0; for (let d = startOfDay(now); activeDates.has(format(d, 'yyyy-MM-dd')); d = subDays(d, 1)) current += 1;
  const sorted = [...activeDates].sort(); let best = 0; let run = 0; let previous = null;
  sorted.forEach((key) => { const date = parseISO(key); run = previous && Math.round((date - previous) / 86400000) === 1 ? run + 1 : 1; best = Math.max(best, run); previous = date; });
  return { today: within(startOfDay(now)), week: within(startOfWeek(now, { weekStartsOn: 1 })), month: within(startOfMonth(now)), total, average: completed.length ? Math.round(total / completed.length) : 0, longest: Math.max(0, ...completed.map(minutes)), current, best, completed };
}

export default function StudyHistory() {
  const [records, setRecords] = useState([]); const [cursor, setCursor] = useState(null); const [hasMore, setHasMore] = useState(true);
  const [subject, setSubject] = useState('All'); const [period, setPeriod] = useState('all'); const [sort, setSort] = useState('newest'); const [search, setSearch] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [selected, setSelected] = useState(null); const sentinel = useRef(null);
  const load = useCallback(async (nextCursor = null) => { const page = await firebaseApi.studyHistory.getPage({ cursor: nextCursor, pageSize: 25 }); setRecords((old) => nextCursor ? [...old, ...page.records.filter((r) => !old.some((o) => o.id === r.id))] : page.records); setCursor(page.cursor); setHasMore(page.hasMore); }, []);
  useEffect(() => { load().catch(() => {}); const unsubscribe = firebaseApi.studyHistory.subscribe((live) => setRecords((old) => [...live, ...old.filter((item) => !live.some((liveItem) => liveItem.id === item.id))])); return unsubscribe; }, [load]);
  useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting && hasMore) load(cursor).catch(() => {}); }); if (sentinel.current) observer.observe(sentinel.current); return () => observer.disconnect(); }, [cursor, hasMore, load]);
  const filtered = useMemo(() => {
    const range = rangeFor(period, from, to); const needle = search.trim().toLowerCase();
    return records.filter((item) => (subject === 'All' || item.subject === subject) && (!range || isWithinInterval(asDate(item), range)) && (!needle || [item.subject, item.topic, item.date].filter(Boolean).join(' ').toLowerCase().includes(needle))).sort((a, b) => sort === 'oldest' ? asDate(a) - asDate(b) : sort === 'longest' ? minutes(b) - minutes(a) : asDate(b) - asDate(a));
  }, [records, subject, period, search, from, to, sort]);
  const stats = useMemo(() => calculateStats(records), [records]);
  const pie = useMemo(() => ['PSAD', 'MSTE', 'HGE'].map((name) => ({ name, value: stats.completed.filter((item) => item.subject === name).reduce((sum, item) => sum + minutes(item), 0) })), [stats]);
  const daily = useMemo(() => eachDayOfInterval({ start: subDays(startOfDay(new Date()), 6), end: startOfDay(new Date()) }).map((day) => ({ name: format(day, 'EEE'), hours: +(stats.completed.filter((item) => isSameDay(asDate(item), day)).reduce((sum, item) => sum + minutes(item), 0) / 60).toFixed(1) })), [stats]);
  const monthDays = useMemo(() => eachDayOfInterval({ start: startOfMonth(new Date()), end: endOfMonth(new Date()) }), []);
  return <div className="space-y-5">
    <div className="flex items-center gap-3"><div className="flex-1"><h1 className="text-2xl font-bold">Study History</h1><p className="text-sm text-muted-foreground">Your synced study sessions</p></div><CalendarDays className="text-primary" /></div>
    <section className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Today', stats.today], ['This week', stats.week], ['This month', stats.month], ['Total', stats.total]].map(([label, value]) => <div className="glass-card p-3" key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="text-lg font-bold">{duration(value)}</p></div>)}</section>
    <section className="glass-card p-4 space-y-3"><div className="flex items-center gap-2"><SlidersHorizontal className="w-4 h-4" /><h2 className="font-semibold">Filters</h2></div><div className="flex gap-2 overflow-x-auto pb-1">{subjects.map((name) => <Button key={name} size="sm" variant={subject === name ? 'default' : 'outline'} onClick={() => setSubject(name)}>{name}</Button>)}</div><div className="grid grid-cols-2 md:grid-cols-4 gap-2"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={period} onChange={(e) => setPeriod(e.target.value)}><option value="all">All time</option><option value="today">Today</option><option value="week">This week</option><option value="month">This month</option><option value="custom">Custom dates</option></select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={sort} onChange={(e) => setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="longest">Longest session</option></select>{period === 'custom' && <><Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /><Input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></>}<div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-muted-foreground" /><Input className="pl-9" placeholder="Subject, topic, date" value={search} onChange={(e) => setSearch(e.target.value)} /></div></div></section>
    <section className="grid md:grid-cols-2 gap-4"><div className="glass-card p-4"><h2 className="font-semibold">Sessions per subject</h2><div className="h-48"><ResponsiveContainer><PieChart><Pie data={pie} dataKey="value" nameKey="name" outerRadius={70}>{pie.map((entry) => <Cell key={entry.name} fill={COLORS[entry.name]} />)}</Pie><Tooltip formatter={(value) => duration(value)} /></PieChart></ResponsiveContainer></div><div className="flex justify-center gap-3 text-xs">{pie.map((item) => <span key={item.name} style={{ color: COLORS[item.name] }}>{item.name}: {duration(item.value)}</span>)}</div></div><div className="glass-card p-4"><h2 className="font-semibold">Daily study hours</h2><div className="h-52"><ResponsiveContainer><BarChart data={daily}><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="hours" fill="#8b5cf6" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></div></div></section>
    <section className="glass-card p-4"><h2 className="font-semibold">Study time overview</h2><div className="h-44"><ResponsiveContainer><BarChart data={[{ period: 'Today', hours: +(stats.today / 60).toFixed(1) }, { period: 'This week', hours: +(stats.week / 60).toFixed(1) }, { period: 'This month', hours: +(stats.month / 60).toFixed(1) }]}><XAxis dataKey="period" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="hours" fill="#3b82f6" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></div></section>
    <section className="glass-card p-4"><h2 className="font-semibold mb-3">Study calendar</h2><div className="grid grid-cols-7 gap-1 text-center text-xs">{['M','T','W','T','F','S','S'].map((day, index) => <span key={`${day}${index}`} className="text-muted-foreground">{day}</span>)}{Array.from({ length: (startOfMonth(new Date()).getDay() + 6) % 7 }).map((_, i) => <span key={`blank${i}`} />)}{monthDays.map((day) => { const sessions = stats.completed.filter((item) => isSameDay(asDate(item), day)); const total = sessions.reduce((sum, item) => sum + minutes(item), 0); const dominant = ['PSAD','MSTE','HGE'].sort((a,b) => sessions.filter(s => s.subject === b).length - sessions.filter(s => s.subject === a).length)[0]; return <button key={day.toISOString()} onClick={() => setPeriod('custom') || setFrom(format(day, 'yyyy-MM-dd')) || setTo(format(day, 'yyyy-MM-dd'))} className={`min-h-12 rounded-lg p-1 ${total ? 'bg-primary/15 hover:bg-primary/25' : 'hover:bg-muted'}`}><b>{format(day, 'd')}</b>{total > 0 && <span className="block text-[9px] text-primary">{duration(total)}<br />{dominant}</span>}</button>; })}</div></section>
    <section className="space-y-3"><div className="flex items-baseline justify-between"><h2 className="text-lg font-bold">Sessions</h2><span className="text-sm text-muted-foreground">{filtered.length} shown</span></div>{filtered.map((item) => <motion.button layout key={item.id} onClick={() => setSelected(item)} className="w-full text-left glass-card p-4 hover:ring-1 hover:ring-primary/40 transition"><div className="flex justify-between gap-3"><div><p className="font-semibold">📘 {item.subject || 'General'}</p>{item.topic && <p className="text-sm text-muted-foreground mt-1">{item.topic}</p>}<p className="mt-2 text-sm">🕒 {format(asDate(item), 'h:mm a')} - {format(parseISO(item.endTime || item.startTime), 'h:mm a')}</p></div><div className="text-right"><p className="font-semibold">⏱ {duration(minutes(item))}</p><p className={item.completed ? 'text-emerald-500 text-sm mt-2' : 'text-amber-500 text-sm mt-2'}>{item.completed ? '✔ Completed' : 'Ended early'}</p><p className="text-xs text-muted-foreground mt-2">{format(asDate(item), 'MMM d, yyyy')}</p></div></div></motion.button>)}<div ref={sentinel} className="h-8 text-center text-xs text-muted-foreground">{hasMore ? 'Loading more…' : 'End of history'}</div></section>
    <section className="grid grid-cols-2 md:grid-cols-4 gap-3"><div className="glass-card p-3"><p className="text-xs text-muted-foreground">Average</p><b>{duration(stats.average)}</b></div><div className="glass-card p-3"><p className="text-xs text-muted-foreground">Longest</p><b>{duration(stats.longest)}</b></div><div className="glass-card p-3"><p className="text-xs text-muted-foreground">Current streak</p><b>{stats.current} days</b></div><div className="glass-card p-3"><p className="text-xs text-muted-foreground">Best streak</p><b>{stats.best} days</b></div></section>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent>{selected && <><DialogHeader><DialogTitle>{selected.subject} session</DialogTitle></DialogHeader><dl className="grid grid-cols-2 gap-3 text-sm"><dt className="text-muted-foreground">Topic</dt><dd>{selected.topic || '—'}</dd><dt className="text-muted-foreground">Start</dt><dd>{format(asDate(selected), 'PPp')}</dd><dt className="text-muted-foreground">End</dt><dd>{format(parseISO(selected.endTime || selected.startTime), 'PPp')}</dd><dt className="text-muted-foreground">Duration</dt><dd>{duration(minutes(selected))}</dd><dt className="text-muted-foreground">Break count</dt><dd>{selected.interruptionCount || 0}</dd><dt className="text-muted-foreground">Pause count</dt><dd>{selected.pausedCount || 0}</dd><dt className="text-muted-foreground">Status</dt><dd>{selected.completed ? 'Completed' : 'Ended early'}</dd><dt className="text-muted-foreground">AI Notes</dt><dd>{selected.notes || 'Coming soon'}</dd></dl></>}</DialogContent></Dialog>
  </div>;
}
