import React, { useEffect, useMemo, useRef, useState } from 'react';
import { firebaseApi } from '@/api/firebaseClient';
import { blankFormula, blankQuestion, extractImport, FORMULA_IMPORT_ACCEPT, IMPORT_ACCEPT, normalizeItem, validateItem } from '@/lib/importEngine';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/components/ui/use-toast';
import { Check, FileUp, Loader2, Pencil, Plus, Search, Sparkles, Trash2 } from 'lucide-react';
import TemplateGuide from '@/components/TemplateGuide';

const formulaFields = [['subject', 'Subject'], ['topic', 'Topic'], ['subtopic', 'Subtopic'], ['name', 'Formula name'], ['formula', 'Formula (LaTeX supported)'], ['description', 'Description'], ['variables', 'Variables'], ['units', 'Units'], ['conditions', 'Conditions'], ['applications', 'Applications'], ['exampleProblem', 'Example problem'], ['solution', 'Complete solution'], ['finalAnswer', 'Final answer'], ['commonMistakes', 'Common mistakes'], ['relatedFormulas', 'Related formulas'], ['references', 'References'], ['tags', 'Tags (comma separated)']];
const questionFields = [['subject', 'Subject'], ['topic', 'Topic'], ['difficulty', 'Difficulty'], ['question', 'Question'], ['choices', 'Choices A-D (separate with |)'], ['correctAnswer', 'Correct answer'], ['explanation', 'Explanation'], ['formulaReferences', 'Formula references'], ['tags', 'Tags (comma separated)'], ['boardYear', 'Board year'], ['source', 'Source'], ['images', 'Image URLs (separate with |)'], ['attachments', 'Attachment URLs (separate with |)']];

export default function ContentLibrary({ type }) {
  const isFormula = type === 'formula';
  const Entity = isFormula ? firebaseApi.entities.Formula : firebaseApi.entities.Question;
  const singular = isFormula ? 'Formula' : 'Question';
  const makeBlank = isFormula ? blankFormula : blankQuestion;
  const fields = isFormula ? formulaFields : questionFields;
  const acceptedFiles = isFormula ? FORMULA_IMPORT_ACCEPT : IMPORT_ACCEPT;
  const [user, setUser] = useState(null); const [items, setItems] = useState([]); const [draft, setDraft] = useState(makeBlank());
  const [editing, setEditing] = useState(null); const [mode, setMode] = useState('manual'); const [open, setOpen] = useState(false);
  const [search, setSearch] = useState(''); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState([]);
  const [ai, setAi] = useState({ subject: '', topic: '', difficulty: 'medium', count: 5 }); const fileRef = useRef(null); const { toast } = useToast();
  useEffect(() => { (async () => { const me = await firebaseApi.auth.me(); setUser(me); setItems(await Entity.filter({ user_id: me.id })); })(); }, [type]);
  const filtered = useMemo(() => { const q = search.toLowerCase(); return items.filter(x => !q || [x.name, x.subject, x.topic, x.question, x.tags, x.source].join(' ').toLowerCase().includes(q)); }, [items, search]);
  const setField = (key, value) => setDraft(p => ({ ...p, [key]: value }));
  const save = async () => {
    const validation = validateItem(draft, type); if (!validation.valid) return toast({ title: `Complete: ${validation.missing.join(', ')}`, variant: 'destructive' });
    const payload = { ...draft, user_id: user.id, tags: typeof draft.tags === 'string' ? draft.tags.split(',').map(x => x.trim()).filter(Boolean) : draft.tags, images: typeof draft.images === 'string' ? draft.images.split('|').map(x => x.trim()).filter(Boolean) : draft.images, attachments: typeof draft.attachments === 'string' ? draft.attachments.split('|').map(x => x.trim()).filter(Boolean) : draft.attachments };
    if (editing?.id) { const updated = await Entity.update(editing.id, payload); setItems(p => p.map(x => x.id === editing.id ? { ...x, ...updated } : x)); }
    else { const created = await Entity.create(payload); setItems(p => [created, ...p]); }
    setOpen(false); setEditing(null); setDraft(makeBlank()); toast({ title: `${singular} saved` });
  };
  const generate = async () => { setBusy(true); try {
    const result = await firebaseApi.integrations.Core.InvokeLLM({
      prompt: `Generate ${ai.count} CELE ${isFormula ? 'formulas' : 'multiple choice questions'} for Subject: ${ai.subject}; Topic: ${ai.topic}; Difficulty: ${ai.difficulty}. Return content ready for review. ${isFormula ? 'Each item needs name, subject, topic, subtopic, formula, description, variables, units, conditions, applications, exampleProblem, solution, finalAnswer, commonMistakes, relatedFormulas, references, tags.' : 'Each needs subject, topic, difficulty, question, choices (four strings), correctAnswer, explanation, formulaReferences, tags, boardYear, source.'}`,
      response_json_schema: { type: 'object', properties: { items: { type: 'array', items: { type: 'object' } } } },
    }); setPreview((result.items || []).map(x => normalizeItem(x, type, 'ai'))); setMode('review');
  } catch (e) { toast({ title: e.message || 'AI generation failed', variant: 'destructive' }); } finally { setBusy(false); } };
  const importFile = async (file) => { if (!file || !user) return; setBusy(true); try { setPreview(await extractImport({ file, type, userId: user.id })); setMode('review'); } catch (e) { toast({ title: e.message || 'Import failed', variant: 'destructive' }); } finally { setBusy(false); } };
  const savePreview = async () => { const invalid = preview.map((x, i) => ({ ...validateItem(x, type), i })).filter(x => !x.valid); if (invalid.length) return toast({ title: `${invalid.length} item(s) need required fields before saving`, variant: 'destructive' }); setBusy(true); try { const created = await Entity.bulkCreate(preview.map(x => ({ ...x, user_id: user.id, tags: typeof x.tags === 'string' ? x.tags.split(',').map(t => t.trim()).filter(Boolean) : x.tags }))); setItems(p => [...created, ...p]); setPreview([]); setMode('manual'); toast({ title: `${created.length} ${singular.toLowerCase()}s saved` }); } finally { setBusy(false); } };
  const editPreview = (index, key, value) => setPreview(p => p.map((x, i) => i === index ? { ...x, [key]: value } : x));
  return <div className="space-y-5"><div className="flex flex-wrap gap-3 justify-between"><div><h1 className="text-2xl font-bold">{isFormula ? 'Formula Sheet' : 'Question Bank'}</h1><p className="text-sm text-muted-foreground">Create manually, generate with AI, or import and review files.</p></div><Button onClick={() => { setDraft(makeBlank()); setEditing(null); setOpen(true); }}><Plus className="w-4 h-4 mr-1" />Manual input</Button></div>
    <Tabs value={mode} onValueChange={setMode}><TabsList className="grid grid-cols-3 w-full"><TabsTrigger value="manual">Library</TabsTrigger><TabsTrigger value="ai">AI generated</TabsTrigger><TabsTrigger value="import">File import</TabsTrigger></TabsList>
      {mode === 'manual' && <div className="space-y-4 mt-4"><div className="relative"><Search className="absolute w-4 h-4 left-3 top-3 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search subject, topic, tags, or content"/></div><div className="grid gap-3 md:grid-cols-2">{filtered.map(item => <article key={item.id} className="glass-card p-4"><div className="flex gap-2 justify-between"><div><h2 className="font-semibold">{item.name || item.question}</h2><p className="text-xs text-muted-foreground">{item.subject} · {item.topic} · {item.sourceType || 'manual'}</p></div><div className="flex"><Button variant="ghost" size="icon" onClick={() => { setDraft({ ...item, tags: Array.isArray(item.tags) ? item.tags.join(', ') : item.tags }); setEditing(item); setOpen(true); }}><Pencil className="w-4 h-4"/></Button><Button variant="ghost" size="icon" onClick={async () => { await Entity.delete(item.id); setItems(p => p.filter(x => x.id !== item.id)); }}><Trash2 className="w-4 h-4"/></Button></div></div><p className="text-sm mt-2 whitespace-pre-wrap">{item.formula || item.explanation}</p></article>)}</div>{!filtered.length && <p className="py-10 text-center text-muted-foreground">No {singular.toLowerCase()}s yet.</p>}</div>}
      {mode === 'ai' && <div className="mt-4 glass-card p-5 space-y-3"><Input placeholder="Subject" value={ai.subject} onChange={e => setAi(p => ({ ...p, subject: e.target.value }))}/><Input placeholder="Topic" value={ai.topic} onChange={e => setAi(p => ({ ...p, topic: e.target.value }))}/><div className="grid grid-cols-2 gap-3"><Input placeholder="Difficulty" value={ai.difficulty} onChange={e => setAi(p => ({ ...p, difficulty: e.target.value }))}/><Input type="number" min="1" max="50" value={ai.count} onChange={e => setAi(p => ({ ...p, count: Number(e.target.value) }))}/></div><Button onClick={generate} disabled={busy || !ai.subject || !ai.topic}>{busy ? <Loader2 className="w-4 h-4 animate-spin mr-2"/> : <Sparkles className="w-4 h-4 mr-2"/>}Generate for review</Button></div>}
      {mode === 'import' && <div className="mt-4 glass-card p-6 space-y-5"><TemplateGuide type={type} /><div className="text-center"><FileUp className="w-10 h-10 mx-auto mb-3 text-primary"/><p>{isFormula ? 'PDF, DOCX, XLSX, CSV, TXT, JPG, or PNG' : 'PDF, DOCX, TXT, CSV, XLSX, JPG, PNG, or WEBP'}</p><p className="text-xs text-muted-foreground mt-1">OCR, AI template mapping, quality checks, duplicate detection, and template normalization are applied before saving.</p><input ref={fileRef} type="file" accept={acceptedFiles} className="hidden" onChange={e => importFile(e.target.files?.[0])}/><Button className="mt-4" onClick={() => fileRef.current?.click()} disabled={busy}>{busy && <Loader2 className="w-4 h-4 animate-spin mr-2"/>}Choose file</Button></div></div>}
      {mode === 'review' && <div className="mt-4 space-y-3"><div className="flex justify-between items-center"><p className="font-medium">Review extracted/generated items ({preview.length})</p><Button onClick={savePreview} disabled={busy || !preview.length}><Check className="w-4 h-4 mr-1"/>Save validated items</Button></div><p className="text-xs text-muted-foreground">🟢 mapped and ready · 🟡 required fields missing · 🔴 low confidence - confirm before saving</p>{preview.map((item, index) => { const status = validateItem(item, type); const lowConfidence = (item.confidence ?? 1) < 0.8; const state = lowConfidence ? 'border-destructive/70 bg-destructive/5' : !status.valid ? 'border-yellow-500/70 bg-yellow-500/5' : 'border-green-500/60 bg-green-500/5'; return <div key={index} className={`glass-card border p-4 space-y-2 ${state}`}><p className="text-xs text-muted-foreground">{lowConfidence ? '🔴' : !status.valid ? '🟡' : '🟢'} Confidence: {Math.round((item.confidence ?? 1) * 100)}% {!status.valid && ` · Missing: ${status.missing.join(', ')}`}</p>{fields.map(([key, label]) => <div key={key}><Label className="text-xs">{label}</Label>{key === 'question' || key === 'formula' || key === 'description' || key === 'explanation' || key === 'solution' || key === 'exampleProblem' ? <Textarea value={item[key] || ''} onChange={e => editPreview(index, key, e.target.value)}/> : <Input value={key === 'choices' ? (item.choices || []).join(' | ') : Array.isArray(item[key]) ? item[key].join(' | ') : item[key] || ''} onChange={e => editPreview(index, key, key === 'choices' || ['images', 'attachments'].includes(key) ? e.target.value.split('|').map(x => x.trim()) : e.target.value)}/>}</div>)}</div>; })}</div>}
    </Tabs>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{editing ? `Edit ${singular}` : `New ${singular}`}</DialogTitle></DialogHeader><div className="space-y-3">{fields.map(([key, label]) => <div key={key}><Label>{label}</Label>{key === 'question' || key === 'formula' || key === 'description' || key === 'explanation' || key === 'solution' || key === 'exampleProblem' ? <Textarea value={draft[key] || ''} onChange={e => setField(key, e.target.value)}/> : <Input value={key === 'choices' ? draft.choices.join(' | ') : ['images', 'attachments'].includes(key) && Array.isArray(draft[key]) ? draft[key].join(' | ') : draft[key] || ''} onChange={e => setField(key, key === 'choices' || ['images', 'attachments'].includes(key) ? e.target.value.split('|').map(x => x.trim()).filter(Boolean) : e.target.value)}/>}</div>)}<Button onClick={save} className="w-full">Save {singular}</Button></div></DialogContent></Dialog>
  </div>;
}
