import React, { useState } from 'react';
import { Download, Expand, Loader2, Maximize2, Minus, Plus, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';

export default function EngineeringIllustration({ imageUrl, caption, onRegenerate, generating = false }) {
  const [open, setOpen] = useState(false);
  const [zoom, setZoom] = useState(1);
  const fullscreen = () => document.fullscreenElement ? document.exitFullscreen() : document.getElementById('engineering-illustration-viewer')?.requestFullscreen?.();
  if (!imageUrl && !generating) return null;
  return <section className="mt-3 rounded-lg border bg-muted/20 p-3"><div className="mb-2 flex items-center justify-between gap-2"><h3 className="text-sm font-semibold">Engineering Illustration</h3><div className="flex gap-1"><Button type="button" variant="ghost" size="icon" aria-label="Fullscreen illustration" onClick={() => setOpen(true)} disabled={!imageUrl}><Maximize2 className="h-4 w-4" /></Button>{imageUrl && <Button type="button" variant="ghost" size="icon" asChild aria-label="Download illustration"><a href={imageUrl} download="engineering-illustration.png" target="_blank" rel="noreferrer"><Download className="h-4 w-4" /></a></Button>}<Button type="button" variant="ghost" size="icon" aria-label="Regenerate illustration" onClick={onRegenerate} disabled={generating}><RefreshCw className={`h-4 w-4 ${generating ? 'animate-spin' : ''}`} /></Button></div></div>{generating ? <div className="flex h-44 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div> : <><img src={imageUrl} alt={caption} className="max-h-80 w-full cursor-zoom-in object-contain" onClick={() => setOpen(true)} /><p className="mt-2 text-xs text-muted-foreground">{caption}</p></>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-5xl"><DialogHeader><DialogTitle>Engineering Illustration</DialogTitle></DialogHeader><div id="engineering-illustration-viewer" className="relative max-h-[78vh] overflow-auto bg-muted/30"><div className="sticky top-2 z-10 flex justify-end gap-1 p-2"><Button type="button" variant="outline" size="icon" aria-label="Zoom out" onClick={() => setZoom((value) => Math.max(.5, value - .25))}><Minus className="h-4 w-4" /></Button><Button type="button" variant="outline" size="icon" aria-label="Zoom in" onClick={() => setZoom((value) => Math.min(3, value + .25))}><Plus className="h-4 w-4" /></Button><Button type="button" variant="outline" size="icon" aria-label="Fullscreen" onClick={fullscreen}><Expand className="h-4 w-4" /></Button></div><img src={imageUrl} alt={caption} style={{ transform: `scale(${zoom})`, transformOrigin: 'top center' }} className="mx-auto max-h-[75vh] w-full object-contain transition-transform" /></div></DialogContent></Dialog></section>;
}
