import React, { useEffect, useMemo, useState } from 'react';
import { firebaseApi } from '@/api/firebaseClient';
import { Button } from '@/components/ui/button';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useToast } from '@/components/ui/use-toast';
import RemoteFigure from '@/components/RemoteFigure';
import SituationViewer from '@/components/SituationViewer';
import { LatexText } from '@/components/LatexFormula';

const sources = [{ value: 'manual', label: 'Manual Only' }, { value: 'ai', label: 'AI Only' }, { value: 'imported', label: 'Imported Only' }, { value: 'mixed', label: 'Mixed' }];
const subjects = ['all', 'PSAD', 'MSTE', 'HGE'];

export default function QuestionSession({ exam = false }) {
  const [user, setUser] = useState(null); const [source, setSource] = useState('mixed'); const [subject, setSubject] = useState('all'); const [count, setCount] = useState(exam ? 50 : 10); const [active, setActive] = useState(null); const [situations, setSituations] = useState([]); const [answers, setAnswers] = useState({}); const [submitted, setSubmitted] = useState(false); const { toast } = useToast();
  useEffect(() => { firebaseApi.auth.me().then(setUser); }, []);
  const selected = useMemo(() => active?.slice(0, count) || [], [active, count]);
  const groups = useMemo(() => { const lookup = new Map(situations.map((item) => [item.id, item])); const map = new Map(); const singles = []; selected.forEach((question, index) => { if (question.situationId && lookup.has(question.situationId)) map.set(question.situationId, [...(map.get(question.situationId) || []), { question, index }]); else singles.push({ entries: [{ question, index }] }); }); const result = []; const seen = new Set(); selected.forEach((question) => { if (map.has(question.situationId)) { if (!seen.has(question.situationId)) { result.push({ situation: lookup.get(question.situationId), entries: map.get(question.situationId).sort((a, b) => Number(a.question.questionNumber || 0) - Number(b.question.questionNumber || 0)) }); seen.add(question.situationId); } } else result.push(singles.find((entry) => entry.entries[0].question.id === question.id)); }); return result.filter(Boolean); }, [selected, situations]);
  const start = async () => { if (!user) return; const all = await firebaseApi.entities.Question.filter({ user_id: user.id }); const eligible = all.filter((question) => (source === 'mixed' || question.sourceType === source) && (subject === 'all' || question.subject === subject)); if (!eligible.length) return toast({ title: 'No questions match these selections', variant: 'destructive' }); setActive([...eligible].sort(() => Math.random() - 0.5)); setSituations(await firebaseApi.entities.Situation.filter({ user_id: user.id })); setAnswers({}); setSubmitted(false); };
  const correct = (question, answer) => String(answer || '').trim().toLowerCase() === String(question.correctAnswer || '').trim().toLowerCase() || question.choices?.[Number(String(question.correctAnswer).charCodeAt(0)) - 65] === answer;
  const finish = async () => { const score = selected.filter((question, index) => correct(question, answers[index])).length; const record = { user_id: user.id, source, subject, questionCount: selected.length, correct: score, score: selected.length ? Math.round(score / selected.length * 100) : 0, completedAt: new Date().toISOString() }; await (exam ? firebaseApi.entities.ExamResult : firebaseApi.entities.PracticeHistory).create(record); await firebaseApi.entities.UserQuestionHistory.bulkCreate(selected.map((question, index) => ({ user_id: user.id, questionId: question.id, selectedAnswer: answers[index] || '', isCorrect: correct(question, answers[index]), mode: exam ? 'mock_exam' : 'practice' }))); setSubmitted(true); };
  const Question = ({ question, index }) => <article className="rounded-lg border bg-background/40 p-3" key={question.id}>{question.imageUrl && <RemoteFigure url={question.imageUrl} label={question.figureLabel || 'Question figure'} />}<p className="mt-2 font-medium">{index + 1}. <LatexText value={question.question} /></p><RadioGroup value={answers[index] || ''} onValueChange={(value) => setAnswers((previous) => ({ ...previous, [index]: value }))} disabled={submitted} className="mt-2 grid gap-1.5">{(question.choices || []).map((choice, choiceIndex) => <div className="flex items-center gap-2" key={choiceIndex}><RadioGroupItem value={choice} id={`${question.id}-${choiceIndex}`} /><Label htmlFor={`${question.id}-${choiceIndex}`}>{String.fromCharCode(65 + choiceIndex)}. <LatexText value={choice} /></Label></div>)}</RadioGroup>{submitted && <div className="mt-2 text-sm"><p className="font-medium">Answer: <LatexText value={question.correctAnswer} /></p>{question.explanation && <p className="text-muted-foreground"><LatexText value={question.explanation} /></p>}</div>}</article>;
  if (!active) return <div className="space-y-4"><div><h1 className="text-2xl font-bold">{exam ? 'Mock Board Exam' : 'Practice Mode'}</h1><p className="text-sm text-muted-foreground">Choose a subject, then practice grouped board-exam situations.</p></div><div className="glass-card space-y-3 p-4"><div><Label>{exam ? 'Exam mode' : 'Subject'}</Label><Select value={subject} onValueChange={setSubject}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{subjects.map((value) => <SelectItem key={value} value={value}>{exam && value === 'all' ? 'Full Board Exam' : value === 'all' ? 'All Subjects' : `${value}${exam ? ' Only' : ''}`}</SelectItem>)}</SelectContent></Select></div><div><Label>Question source</Label><Select value={source} onValueChange={setSource}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{sources.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div><div><Label>Question count</Label><Select value={String(count)} onValueChange={(value) => setCount(Number(value))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{[5, 10, 25, 50, 100].map((number) => <SelectItem key={number} value={String(number)}>{number}</SelectItem>)}</SelectContent></Select></div><Button onClick={start}>Start {exam ? 'exam' : 'practice'}</Button></div></div>;
  return <div className="space-y-4"><div className="flex justify-between text-sm"><span>{selected.length} questions · {subject === 'all' ? 'All subjects' : subject}</span>{submitted && <span className="font-semibold">Score: {selected.length ? Math.round(selected.filter((question, index) => correct(question, answers[index])).length / selected.length * 100) : 0}%</span>}</div>{groups.map((group) => group.situation ? <SituationViewer key={group.situation.id} situation={group.situation}><div className="space-y-2">{group.entries.map((entry) => <Question {...entry} key={entry.question.id} />)}</div></SituationViewer> : group.entries.map((entry) => <Question {...entry} key={entry.question.id} />))}<div className="flex gap-2"><Button onClick={finish} disabled={submitted}>Submit</Button><Button variant="outline" onClick={() => setActive(null)}>New session</Button></div></div>;
}
