import React, { useEffect, useMemo, useState } from 'react';
import { firebaseApi } from '@/api/firebaseClient';
import { Button } from '@/components/ui/button';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useToast } from '@/components/ui/use-toast';

const sources = [{ value: 'manual', label: 'Manual Only' }, { value: 'ai', label: 'AI Only' }, { value: 'imported', label: 'Imported Only' }, { value: 'mixed', label: 'Mixed' }];
export default function QuestionSession({ exam = false }) {
  const [user, setUser] = useState(null); const [questions, setQuestions] = useState([]); const [source, setSource] = useState('mixed');
  const [count, setCount] = useState(exam ? 50 : 10); const [active, setActive] = useState(null); const [answers, setAnswers] = useState({}); const [submitted, setSubmitted] = useState(false); const { toast } = useToast();
  useEffect(() => { firebaseApi.auth.me().then(setUser); }, []);
  const selected = useMemo(() => active?.filter(q => source === 'mixed' || q.sourceType === source).slice(0, count) || [], [active, source, count]);
  const start = async () => { if (!user) return; const all = await firebaseApi.entities.Question.filter({ user_id: user.id }); const eligible = all.filter(q => source === 'mixed' || q.sourceType === source); if (!eligible.length) return toast({ title: 'No questions available for this source', variant: 'destructive' }); setQuestions(eligible.sort(() => Math.random() - 0.5)); setActive(eligible.sort(() => Math.random() - 0.5)); setAnswers({}); setSubmitted(false); };
  const finish = async () => { const run = selected; const correct = run.filter((q, i) => String(answers[i] || '').trim().toLowerCase() === String(q.correctAnswer || '').trim().toLowerCase() || q.choices?.[Number(String(q.correctAnswer).charCodeAt(0)) - 65] === answers[i]).length; const payload = { user_id: user.id, source, questionCount: run.length, correct, score: run.length ? Math.round(correct / run.length * 100) : 0, completedAt: new Date().toISOString() }; await (exam ? firebaseApi.entities.ExamResult : firebaseApi.entities.PracticeHistory).create(payload); await firebaseApi.entities.UserQuestionHistory.bulkCreate(run.map(q => ({ user_id: user.id, questionId: q.id, selectedAnswer: answers[run.indexOf(q)] || '', isCorrect: String(answers[run.indexOf(q)] || '').toLowerCase() === String(q.correctAnswer || '').toLowerCase(), mode: exam ? 'mock_exam' : 'practice' }))); setSubmitted(true); };
  const heading = exam ? 'Mock Board Exam' : 'Practice Mode';
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold">{heading}</h1><p className="text-sm text-muted-foreground">Use questions from any creation method.</p></div>{!active ? <div className="glass-card p-5 space-y-4"><div><Label>Question source</Label><Select value={source} onValueChange={setSource}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{sources.map(s => <SelectItem key={s.value} value={s.value}>{exam ? s.label.replace('Only', 'Database').replace('Mixed', 'Mix Everything') : s.label}</SelectItem>)}</SelectContent></Select></div><div><Label>Question count</Label><Select value={String(count)} onValueChange={v => setCount(Number(v))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[5, 10, 25, 50, 100].map(n => <SelectItem key={n} value={String(n)}>{n}</SelectItem>)}</SelectContent></Select></div><Button onClick={start}>Start {exam ? 'exam' : 'practice'}</Button></div> : <><div className="flex justify-between text-sm"><span>{selected.length} questions · {source}</span>{submitted && <span className="font-semibold">Score: {selected.length ? Math.round(selected.filter((q, i) => String(answers[i] || '').toLowerCase() === String(q.correctAnswer || '').toLowerCase()).length / selected.length * 100) : 0}%</span>}</div>{selected.map((q, index) => <article key={q.id} className="glass-card p-4"><p className="font-medium">{index + 1}. {q.question}</p><RadioGroup value={answers[index] || ''} onValueChange={v => setAnswers(p => ({ ...p, [index]: v }))} disabled={submitted} className="mt-3">{(q.choices || []).map((choice, i) => <div className="flex items-center gap-2" key={i}><RadioGroupItem value={choice} id={`${q.id}-${i}`}/><Label htmlFor={`${q.id}-${i}`}>{String.fromCharCode(65 + i)}. {choice}</Label></div>)}</RadioGroup>{submitted && <div className="mt-3 text-sm"><p className="font-medium">Answer: {q.correctAnswer}</p><p className="text-muted-foreground">{q.explanation}</p></div>}</article>)}<div className="flex gap-2"><Button onClick={finish} disabled={submitted}>Submit</Button><Button variant="outline" onClick={() => setActive(null)}>New session</Button></div></>}</div>;
}
