import React, { useState } from 'react';
import { CELE_TEMPLATES, downloadTemplate } from '@/lib/contentTemplates';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Download, Eye, FileText } from 'lucide-react';

export default function TemplateGuide({ type }) {
  const [open, setOpen] = useState(false); const [downloadOpen, setDownloadOpen] = useState(false); const template = CELE_TEMPLATES[type];
  const formats = <div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => downloadTemplate(type, 'docx')}>Word (.docx)</Button><Button size="sm" onClick={() => downloadTemplate(type, 'xlsx')}>Excel (.xlsx)</Button><Button size="sm" variant="outline" onClick={() => downloadTemplate(type, 'csv')}>CSV</Button></div>;
  const list = (items) => <ul className="space-y-1">{items.map(item => <li key={item}>✔ {item}</li>)}</ul>;
  const questionTemplate = <div className="space-y-5 text-sm"><section className="space-y-2"><h3 className="font-semibold">SUPPORTED DOCUMENT FORMATS</h3>{list(['PDF (.pdf)', 'Microsoft Word (.docx)', 'PowerPoint (.pptx)', 'Excel (.xlsx)', 'CSV (.csv)', 'Text (.txt)'])}</section><section className="space-y-2"><h3 className="font-semibold">SUPPORTED FIGURE / IMAGE FORMATS</h3><p>Figures, engineering drawings, graphs, tables, maps, and diagrams may be attached.</p>{list(['JPG (.jpg)', 'JPEG (.jpeg)', 'PNG (.png)', 'WEBP (.webp)'])}<p className="font-medium">Recommended</p><ul className="list-disc pl-5 space-y-1"><li>High-resolution images</li><li>Clear black text on white background</li><li>Do not crop figures</li><li>One figure per image whenever possible</li></ul></section><section className="space-y-2"><h3 className="font-semibold">AI CAN AUTOMATICALLY EXTRACT</h3>{list(['Situation Descriptions', 'Standalone Questions', 'Situation-Based Questions', 'Engineering Figures', 'Structural Drawings', 'Survey Maps', 'Tables', 'Graphs', 'Mathematical Equations', 'Question Numbers', 'Choices', 'Correct Answers', 'Explanations', 'Formula References'])}</section><section><h3 className="font-semibold">QUESTION BANK TEMPLATE</h3><p className="mt-2">Question Type</p><p>☐ Standalone Question</p><p>☐ Situation-Based Question</p></section><section><h3 className="font-semibold">STANDALONE QUESTION</h3>{['Subject', 'Topic', 'Difficulty', 'Question', 'Choice A', 'Choice B', 'Choice C', 'Choice D', 'Correct Answer', 'Explanation (Optional)', 'Formula Reference (Optional)', 'Figure/Image (Optional)'].map(field => <p key={field}>{field}:</p>)}</section><section><h3 className="font-semibold">SITUATION-BASED QUESTION</h3>{['Subject', 'Topic', 'Difficulty', 'Situation Description', 'Figure/Image (Optional)'].map(field => <p key={field}>{field}:</p>)}{Array.from({ length: 10 }, (_, i) => <div className="border-t mt-3 pt-3" key={i}><p className="font-medium">Question {i + 1}</p>{['Choice A', 'Choice B', 'Choice C', 'Choice D', 'Correct Answer', 'Explanation (Optional)', 'Formula Reference (Optional)'].map(field => <p key={field}>{field}:</p>)}</div>)}</section><p className="text-muted-foreground">Use only the linked questions needed by your reviewer: Questions 1–3, 1–5, 1–8, or 1–10.</p></div>;
  return <><div className="rounded-xl border border-primary/20 bg-primary/5 p-4 space-y-3"><div className="flex gap-3"><FileText className="w-5 h-5 text-primary shrink-0"/><p className="text-sm">View or download the official CELE Pilot template before uploading. It lists every supported document and figure format and improves extraction accuracy.</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setOpen(true)}><Eye className="w-4 h-4 mr-1"/>View Official Template</Button><Button size="sm" onClick={() => setDownloadOpen(true)}><Download className="w-4 h-4 mr-1"/>Download Official Template</Button></div></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>{template.title}</DialogTitle></DialogHeader><div className="max-h-[55vh] overflow-y-auto rounded-lg bg-muted/50 p-4">{type === 'question' ? questionTemplate : <div className="space-y-2">{template.fields.map(field => <p key={field} className="text-sm font-medium">{field}:</p>)}</div>}</div>{formats}</DialogContent></Dialog><Dialog open={downloadOpen} onOpenChange={setDownloadOpen}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Download official template</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Choose DOCX, XLSX, or CSV. Each includes standalone and situation-based question sections.</p>{formats}</DialogContent></Dialog></>;
}
