import React, { useState } from 'react';
import { CELE_TEMPLATES, downloadTemplate } from '@/lib/contentTemplates';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Download, Eye, FileText } from 'lucide-react';

export default function TemplateGuide({ type }) {
  const [open, setOpen] = useState(false);
  const [downloadOpen, setDownloadOpen] = useState(false);
  const template = CELE_TEMPLATES[type];
  const formats = <div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => downloadTemplate(type, 'docx')}>Word (.docx)</Button><Button size="sm" onClick={() => downloadTemplate(type, 'xlsx')}>Excel (.xlsx)</Button><Button size="sm" variant="outline" onClick={() => downloadTemplate(type, 'csv')}>CSV</Button></div>;
  const questionTemplate = <div className="space-y-5 text-sm"><section className="space-y-2"><h3 className="font-semibold">UNIFIED QUESTION BANK TEMPLATE</h3><p>Use <span className="font-medium">Question Type</span> as the first column. Allowed values: <span className="font-medium">Standalone</span> and <span className="font-medium">Situation</span>.</p><p><span className="font-medium">Standalone</span> → leave all Situation columns blank.</p><p><span className="font-medium">Situation</span> → fill the Situation information and use the same Situation ID for every related question.</p></section><section className="space-y-1"><h3 className="font-semibold">TEMPLATE COLUMNS</h3>{template.fields.map(field => <p key={field}>{field}</p>)}</section><p className="text-muted-foreground">If Question Type is blank during import, the app automatically detects Situation when Situation ID is present; otherwise it treats the row as Standalone.</p></div>;
  return <><div className="rounded-xl border border-primary/20 bg-primary/5 p-4 space-y-3"><div className="flex gap-3"><FileText className="w-5 h-5 text-primary shrink-0"/><p className="text-sm">View or download the official CELE Pilot template before uploading. It lists every supported document and figure format and improves extraction accuracy.</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setOpen(true)}><Eye className="w-4 h-4 mr-1"/>View Official Template</Button><Button size="sm" onClick={() => setDownloadOpen(true)}><Download className="w-4 h-4 mr-1"/>Download Official Template</Button></div></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>{template.title}</DialogTitle></DialogHeader><div className="max-h-[55vh] overflow-y-auto rounded-lg bg-muted/50 p-4">{type === 'question' ? questionTemplate : <div className="space-y-2">{template.fields.map(field => <p key={field} className="text-sm font-medium">{field}:</p>)}</div>}</div>{formats}</DialogContent></Dialog><Dialog open={downloadOpen} onOpenChange={setDownloadOpen}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Download official template</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{type === 'question' ? 'One unified template supports both Standalone and Situation questions.' : 'Choose DOCX, XLSX, or CSV.'}</p>{formats}</DialogContent></Dialog></>;
}
